# Use Node.js
FROM node:20

# Set working folder inside container
WORKDIR /app

# Copy package.json and install dependencies
COPY package*.json ./
RUN npm install

# Copy all frontend code
COPY . .

# Build the app
RUN npm run build

# Use Nginx to serve built app
FROM nginx:alpine
COPY --from=0 /app/dist /usr/share/nginx/html

EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
